#!/bin/zsh

local t=${XDG_CONFIG_HOME}/alacritty/alacritty.toml
local fontsize="$(cat "$t" | grep 'size = ')"
if [[ $fontsize == "size = 18" ]]; then
  gsed -i 's/size = 18/size = 15/g' $t
else
  gsed -i 's/size = 15/size = 18/g' $t
fi
