export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export FPATH="$ZDOTDIR/autoload/:$FPATH"
export TMUX_PLUGIN_MANAGER_PATH="$XDG_DATA_HOME/tmux/plugins"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
